"""Table-level schema and naming contracts for pipeline storage."""

from .tils.til_tables import (
	TIL_CHUNKS_TABLE,
	TIL_CHUNKS_TABLE_DDL_COLS,
	TIL_ELEMENTS_TABLE,
	TIL_ELEMENTS_TABLE_DDL_COLS,
	TIL_EVALUATION_RESULTS_TABLE,
	TIL_EVALUATION_RESULTS_TABLE_DDL_COLS,
	TIL_METADATA_TABLE,
	TIL_METADATA_TABLE_DDL_COLS,
	TIL_PIPELINE_RUN_AUDIT_TABLE,
	TIL_PIPELINE_RUN_AUDIT_TABLE_DDL_COLS,
	TIL_VALIDATION_RESULTS_TABLE,
	TIL_VALIDATION_RESULTS_TABLE_DDL_COLS,
)

__all__ = [
	"TIL_METADATA_TABLE",
	"TIL_ELEMENTS_TABLE",
	"TIL_CHUNKS_TABLE",
	"TIL_VALIDATION_RESULTS_TABLE",
	"TIL_EVALUATION_RESULTS_TABLE",
	"TIL_PIPELINE_RUN_AUDIT_TABLE",
	"TIL_METADATA_TABLE_DDL_COLS",
	"TIL_ELEMENTS_TABLE_DDL_COLS",
	"TIL_CHUNKS_TABLE_DDL_COLS",
	"TIL_VALIDATION_RESULTS_TABLE_DDL_COLS",
	"TIL_EVALUATION_RESULTS_TABLE_DDL_COLS",
	"TIL_PIPELINE_RUN_AUDIT_TABLE_DDL_COLS",
]

